/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BusinessCard: typeof import('./src/components/BusinessCard/BusinessCard.vue')['default']
    CollageBlock: typeof import('./src/components/CollageBlock/CollageBlock.vue')['default']
    HighlightTutorial: typeof import('./src/components/HighlightTutorial/HighlightTutorial.vue')['default']
    LoaderBlock: typeof import('./src/components/LoaderBlock/LoaderBlock.vue')['default']
    'LoaderBlock.ce': typeof import('./src/components/LoaderBlock/LoaderBlock.ce.vue')['default']
    MarqueeBlock: typeof import('./src/components/MarqueeBlock/MarqueeBlock.vue')['default']
    MarqueesContainer: typeof import('./src/components/MarqueesContainer/MarqueesContainer.vue')['default']
    PawCursor: typeof import('./src/components/PawCursor/PawCursor.vue')['default']
    ScrollableCarousel: typeof import('./src/components/ScrollableCarousel/ScrollableCarousel.vue')['default']
    ShareButton: typeof import('./src/components/ShareButton/ShareButton.vue')['default']
    TextBlock: typeof import('./src/components/TextBlock/TextBlock.vue')['default']
    TitleBlock: typeof import('./src/components/TitleBlock/TitleBlock.vue')['default']
    VideoBlock: typeof import('./src/components/VideoBlock/VideoBlock.vue')['default']
  }
}
